version: '3'
services:
  daemon:
    image: drone/drone:2
    #volumes:
    #  - ${DRONE_VOLUME_DATA:-./volumes/data}:/data
    environment:
      - DRONE_LOGS_DEBUG=true
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET:-secretchangeme}
      - DRONE_SECRET=${DRONE_RPC_SECRET:-secretchangeme}
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST:-pipeline.domain.net}
      - DRONE_SERVER_PROTO=https
      - DRONE_GITEA_CLIENT_ID=${DRONE_GITEA_CLIENT_ID:-changeme}
      - DRONE_GITEA_CLIENT_SECRET=${DRONE_GITEA_CLIENT_SECRET:-changeme}
      - DRONE_TLS_AUTOCERT=false
      - DRONE_DATABASE_DRIVER=postgres
      - DRONE_DATABASE_DATASOURCE=postgres://${DRONE_CONF_DB_USER:-pipeline}:${DRONE_CONF_DB_PW:-changeme}@${DRONE_CONF_DB_HOST:-postgres}:5432/${DRONE_CONF_DB:-pipeline}?sslmode=disable
      - DRONE_GITEA_SERVER=${DRONE_GITEA_SERVER:-http://gitea}
      - DRONE_USER_CREATE=username:${DRONE_ADMIN:-admin},admin:true
    networks:
      - web
      - databases
      - default
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=web"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:${DRONE_SERVER_HOST:-pipeline.domain.net}"
        - "traefik.frontend.port=80"
networks:
  web:
    external: true
  databases:
    external: true

